# Generated by Django 5.2.11 on 2026-02-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_allergens_category_description_and_more'),
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergen',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allergen',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='allergens', to='catalog.product'),
        ),
    ]
