# Generated by Django 5.2.11 on 2026-02-27 16:00

from django.db import migrations

ALLERGEN_DATA = [
    ('gluten', 'Gluten', 'Found in wheat, rye, barley, oats, spelt, kamut and their derivatives such as flour, bread, pasta, couscous, and baked goods.'),
    ('crustaceans', 'Crustaceans', 'Includes crabs, lobsters, crayfish, shrimps, prawns, and derivatives such as shrimp paste and crustacean stock.'),
    ('eggs', 'Eggs', 'Includes hen eggs and other bird eggs, found in mayonnaise, meringue, pasta, quiche, batter, glazes, and some sauces.'),
    ('fish', 'Fish', 'All species of fish including anchovies, cod, salmon, tuna, and derivatives such as fish sauce, fish oil, and Worcestershire sauce.'),
    ('peanuts', 'Peanuts', 'A legume (not a tree nut), found in peanut butter, groundnut oil, satay sauce, some cereals, and many processed snack foods.'),
    ('soybeans', 'Soybeans', 'Found in tofu, soy sauce, miso, tempeh, edamame, soy milk, soybean oil, and widely used as an emulsifier (lecithin E322).'),
    ('dairy', 'Dairy', 'Milk from cows, goats, and sheep, found in butter, cheese, cream, yoghurt, casein, whey, and lactose-containing products.'),
    ('nuts', 'Tree Nuts', 'Includes almonds, hazelnuts, walnuts, cashews, pecans, brazil nuts, pistachios, macadamia nuts, and products like marzipan and praline.'),
    ('celery', 'Celery', 'Includes celery stalks, leaves, seeds, and celeriac, commonly found in soups, stock cubes, salads, and spice mixes.'),
    ('mustard', 'Mustard', 'Includes mustard seeds, powder, paste, and oil, found in dressings, marinades, curries, sauces, and processed meats.'),
    ('sesame', 'Sesame', 'Includes sesame seeds, tahini, sesame oil, and hummus, found in breads, breadsticks, and many Asian and Middle Eastern dishes.'),
    ('sulphites', 'Sulphites', 'Sulphur dioxide (E220) and sulphites (E221-E228) used as preservatives in wine, beer, dried fruits, pickled foods, and soft drinks. Declarable above 10mg/kg or 10mg/litre.'),
    ('lupin', 'Lupin', 'A legume related to peanuts, found in lupin flour, seeds, and increasingly used in gluten-free and high-protein baked goods and pasta.'),
    ('molluscs', 'Molluscs', 'Includes mussels, oysters, clams, scallops, squid, octopus, and snails, found in seafood dishes, sauces, and oyster sauce.'),
]

def populate_allergens(apps, schema_editor):
    Allergen = apps.get_model('traceability', 'Allergen')
    for key, name, description in ALLERGEN_DATA:
        Allergen.objects.get_or_create(
            name=name,
            defaults={'description': description}
        )


def reverse_allergens(apps, schema_editor):
    Allergen = apps.get_model('traceability', 'Allergen')
    names = [name for _, name, _ in ALLERGEN_DATA]
    Allergen.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0002_allergen_description_allergen_products'),
    ]

    operations = [
        migrations.RunPython(populate_allergens, reverse_allergens),
    ]
