# Generated by Django 5.2.12 on 2026-03-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_best_before_date_product_discount_percentage_and_more'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmstory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'farm stories'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='farmstory',
            old_name='published',
            new_name='is_published',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='product',
        ),
        migrations.AddField(
            model_name='farmstory',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='farmstory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='seasonal_tag',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('autumn_winter', 'Autumn/Winter'), ('spring_summer', 'Spring/Summer'), ('all_year', 'All Year Round')], default='all_year', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
