# Generated by Django 5.2.12 on 2026-04-20 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_enable_pg_trgm'),
        ('community', '0002_alter_farmstory_options_alter_recipe_options_and_more'),
        ('orders', '0005_order_special_instructions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', '-created_at'], name='community_r_product_feac47_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['customer', '-created_at'], name='community_r_custome_1ba705_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['order_item'], name='community_r_order_i_fb0136_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('product', 'customer'), name='uniq_review_product_customer'),
        ),
    ]
