# Generated by Django 5.2.12 on 2026-05-05 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_product_product_season_start_month_1_12_and_more'),
        ('community', '0003_alter_review_options_review_updated_at_and_more'),
        ('orders', '0006_simplify_recurring_order_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='uniq_review_product_customer',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='community_r_custome_1ba705_idx',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='customer',
            new_name='account',
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['account', '-created_at'], name='community_r_account_7f82f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('product', 'account'), name='uniq_review_product_account'),
        ),
    ]
