# Generated by Django 5.2.11 on 2026-02-27 18:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0004_alter_address_options_and_more'),
        ('catalog', '0008_alter_product_updated_at'),
        ('orders', '0001_initial'),
        ('producers', '0005_remove_producer_business_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('customer_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_as_customer', to='addresses.address')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_records', to='orders.order')),
                ('producer_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_as_producer', to='addresses.address')),
            ],
        ),
        migrations.CreateModel(
            name='Surplus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surpluses', to='producers.producer')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='surplus', to='catalog.product')),
            ],
        ),
    ]
