# Generated by Django 5.2.12 on 2026-05-05 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_alter_address_options_and_more'),
        ('sustainability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancerecord',
            name='customer_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distance_as_customer', to='addresses.address'),
        ),
        migrations.AlterField(
            model_name='distancerecord',
            name='producer_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distance_as_producer', to='addresses.address'),
        ),
    ]
