# Generated by Django 5.2.11 on 2026-03-06 12:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_account_type_and_more'),
        ('addresses', '0004_alter_address_options_and_more'),
        ('catalog', '0004_remove_product_best_before_date_and_more'),
        ('orders', '0001_initial'),
        ('producers', '0005_remove_producer_business_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('monthday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('next_run_at', models.DateTimeField(db_index=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payout_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_period', models.DateTimeField()),
                ('end_period', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='producerorder',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='producerorder',
            name='payout_amount',
        ),
        migrations.RemoveField(
            model_name='producerorder',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='producerorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='producerorder',
            constraint=models.UniqueConstraint(fields=('order', 'producer'), name='uniq_order_producer'),
        ),
        migrations.AddField(
            model_name='commissionledger',
            name='producer_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission_ledger', to='orders.producerorder'),
        ),
        migrations.AddField(
            model_name='recurringorder',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_orders', to='addresses.address'),
        ),
        migrations.AddField(
            model_name='recurringorder',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_orders', to='accounts.organisation'),
        ),
        migrations.AddField(
            model_name='recurringorderevent',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_order_event', to='orders.order'),
        ),
        migrations.AddField(
            model_name='recurringorderevent',
            name='recurring_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.recurringorder'),
        ),
        migrations.AddField(
            model_name='recurringorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_order_items', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='recurringorderitem',
            name='recurring_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.recurringorder'),
        ),
        migrations.AddField(
            model_name='settlementline',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_lines', to='producers.producer'),
        ),
        migrations.AddField(
            model_name='commissionledger',
            name='settlement_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.settlementline'),
        ),
        migrations.AddConstraint(
            model_name='weeklysettlement',
            constraint=models.UniqueConstraint(fields=('start_period', 'end_period'), name='uniq_weeklysettlement_period'),
        ),
        migrations.AddField(
            model_name='settlementline',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.weeklysettlement'),
        ),
        migrations.AddIndex(
            model_name='recurringorderevent',
            index=models.Index(fields=['recurring_order', 'scheduled_for'], name='orders_recu_recurri_e3a6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringorderevent',
            index=models.Index(fields=['scheduled_for'], name='orders_recu_schedul_1ff78b_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringorderevent',
            constraint=models.UniqueConstraint(fields=('recurring_order', 'scheduled_for'), name='uniq_recurringorder_scheduledfor'),
        ),
        migrations.AddConstraint(
            model_name='recurringorderitem',
            constraint=models.UniqueConstraint(fields=('recurring_order', 'product'), name='uniq_recurringorder_product'),
        ),
        migrations.AddConstraint(
            model_name='settlementline',
            constraint=models.UniqueConstraint(fields=('settlement', 'producer'), name='uniq_settlement_producer'),
        ),
    ]
