# Generated by Django 5.2.12 on 2026-03-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_commissionledger_recurringorder_recurringorderevent_and_more'),
        ('orders', '0002_order_stripe_session_id'),
    ]

    operations = [
    ]
