# Generated by Django 5.2.12 on 2026-03-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_merge_20260306_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('in transit', 'In Transit'), ('ready for collection', 'Ready for Collection'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
