# Generated by Django 5.2.12 on 2026-03-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringorder',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='recurringorder',
            name='monthday',
        ),
        migrations.RemoveField(
            model_name='recurringorder',
            name='weekday',
        ),
        migrations.AddField(
            model_name='recurringorder',
            name='delivery_day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=2),
        ),
        migrations.AddField(
            model_name='recurringorder',
            name='order_day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AlterField(
            model_name='recurringorder',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly')], max_length=20),
        ),
    ]
