# Generated by Django 5.2.12 on 2026-05-05 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_low_stock_threshold'),
        ('orders', '0005_order_special_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recurringorderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='orderitem_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='recurringorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='recurringorderitem_quantity_gt_0'),
        ),
    ]
