# Generated by Django 5.2.12 on 2026-05-05 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20260327_0807'),
        ('addresses', '0004_alter_address_options_and_more'),
        ('orders', '0006_alter_orderitem_quantity_and_more'),
        ('producers', '0006_remove_producer_company_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recurringorderevent',
            name='uniq_recurringorder_scheduledfor',
        ),
        migrations.RemoveIndex(
            model_name='recurringorderevent',
            name='orders_recu_recurri_e3a6cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='recurringorderevent',
            name='orders_recu_schedul_1ff78b_idx',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'cancelled', 'in transit', 'ready for collection', 'completed'])), name='order_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='producerorder',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'rejected', 'preparing', 'ready', 'delivered', 'cancelled'])), name='producerorder_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='recurringorder',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'paused', 'cancelled'])), name='recurringorder_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='recurringorderevent',
            constraint=models.UniqueConstraint(fields=('recurring_order', 'scheduled_for'), name='uniq_recur_event_schedule'),
        ),
        migrations.AddConstraint(
            model_name='recurringorderevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['created', 'failed', 'skipped'])), name='recur_event_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='settlementline',
            constraint=models.CheckConstraint(condition=models.Q(('payout_status__in', ['pending', 'paid', 'failed'])), name='settlementline_valid_payout_status'),
        ),
        migrations.AddConstraint(
            model_name='weeklysettlement',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'completed', 'failed'])), name='weeklysettlement_valid_status'),
        ),
    ]
