# Generated by Django 5.2.12 on 2026-05-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_simplify_recurring_order_schedule'),
        ('orders', '0007_remove_recurringorderevent_uniq_recurringorder_scheduledfor_and_more'),
    ]

    operations = [
    ]
