# Generated by Django 5.2.12 on 2026-05-06 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_bulk_stock_discount_and_more'),
        ('orders', '0008_merge_20260505_1442'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='uniq_producerorder_product',
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='orderitem_quantity_gt_0',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='recurringorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_order_items', to='catalog.product'),
        ),
    ]
