# Generated by Django 5.2.13 on 2026-05-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_producerorderstatusevent'),
        ('producers', '0006_remove_producer_company_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='producerorder',
            name='producerorder_valid_status',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilment_method',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], default='delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='producerorder',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producerorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('ready for pickup', 'Ready for Pickup'), ('collected', 'Collected'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='producerorder',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'rejected', 'preparing', 'ready', 'ready for pickup', 'collected', 'delivered', 'cancelled'])), name='producerorder_valid_status'),
        ),
    ]
