# Generated by Django 5.2.11 on 2026-02-26 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_allergens_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='best_before_date',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
