# Generated by Django 5.2.11 on 2026-02-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_inventoryadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='reason',
            field=models.CharField(choices=[('order_adjustment', 'Order Adjustment'), ('producer_adjustment_add', 'Producer Adjustment - Adding Stock'), ('producer_adjustment_remove', 'Producer Adjustment - Removing Stock')], max_length=50),
        ),
    ]
