# Generated by Django 5.2.11 on 2026-02-27 15:14

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_inventoryadjustment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now,),
            preserve_default=False,
        ),
    ]
