# Generated by Django 5.2.12 on 2026-03-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability_end',
        ),
        migrations.RemoveField(
            model_name='product',
            name='availability_start',
        ),
        migrations.AddField(
            model_name='product',
            name='availability_mode',
            field=models.CharField(choices=[('year_round', 'Available Year-Round'), ('seasonal', 'In Season')], default='year_round', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='season_end_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='season_start_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
    ]
