# Generated by Django 5.2.12 on 2026-03-23 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_product_availability_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_before_date',
            field=models.DateTimeField(blank=True, help_text='Best before date for perishable products', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage for surplus deal (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='is_surplus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='surplus_end_date',
            field=models.DateTimeField(blank=True, help_text='When the surplus deal expires', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='surplus_note',
            field=models.TextField(blank=True, default='', help_text='Producer note about the surplus deal'),
        ),
    ]
