# Generated by Django 5.2.13 on 2026-04-14 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_enable_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('viewed', 'Clicked to View Product from Recommendations'), ('added_to_cart', 'Added to Cart from Recommendations'), ('purchased', 'Purchased after Recommendation')], max_length=20)),
                ('recommendation_rank', models.PositiveSmallIntegerField()),
                ('reorder_probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_interactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_interactions', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'created_at'], name='catalog_rec_account_945633_idx'), models.Index(fields=['product', 'event_type'], name='catalog_rec_product_a3f9a4_idx')],
            },
        ),
    ]
