# Generated by Django 5.2.12 on 2026-05-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_product_stock_product_product_price_gte_0_and_more'),
        ('producers', '0006_remove_producer_company_email'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('season_start_month__isnull', True), models.Q(('season_start_month__gte', 1), ('season_start_month__lte', 12)), _connector='OR'), name='product_season_start_month_1_12'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('season_end_month__isnull', True), models.Q(('season_end_month__gte', 1), ('season_end_month__lte', 12)), _connector='OR'), name='product_season_end_month_1_12'),
        ),
    ]
