# Generated by Django 5.2.13 on 2026-05-05 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_product_product_season_start_month_1_12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_stock_discount',
            field=models.DecimalField(decimal_places=2, default=5, help_text='percentage discount for quantities above the bulk threshold', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_stock_threshold',
            field=models.PositiveIntegerField(default=20, help_text='quantity needed before bulk pricing applies', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
