# Generated by Django 5.2.11 on 2026-02-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('producer', 'Producer'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
    ]
