# Generated by Django 5.2.11 on 2026-02-26 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_phone_number_and_more'),
        ('addresses', '0004_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='organisation_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='default_delivery_address',
            field=models.ForeignKey(blank=True, limit_choices_to={'address_type': 'DELIVERY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_customers', to='addresses.address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=255)),
                ('organisation_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('organisation_type', models.CharField(blank=True, choices=[('community_group', 'Community Group'), ('restaurant', 'Restaurant'), ('charity', 'Charity'), ('education', 'Education')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='accounts.customer')),
            ],
        ),
    ]
