# Generated by Django 5.2.12 on 2026-03-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='accounts.customer'),
        ),
    ]
