# Generated by Django 5.2.12 on 2026-03-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_organisation_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('producer', 'Producer'), ('restaurant', 'Restaurant'), ('community_group', 'Community Group'), ('admin', 'Admin')], db_index=True, default='customer', max_length=20),
        ),
    ]
