# Generated by Django 5.2.12 on 2026-03-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_account_created_at'),
        ('accounts', '0010_alter_account_account_type'),
    ]

    operations = [
    ]
