# Generated by Django 5.2.11 on 2026-02-20 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-created_at']},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='account',
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('BUSINESS', 'Business')], default='DELIVERY', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['postcode'], name='addresses_a_postcod_7648cf_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['account', 'address_type'], name='addresses_a_account_f918b4_idx'),
        ),
    ]
