# Generated by Django 5.2.11 on 2026-02-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_options_rename_user_address_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', 'created_at']},
        ),
    ]
