# Generated by Django 5.2.11 on 2026-02-19 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='business_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer_business', to='addresses.address'),
        ),
        migrations.AddField(
            model_name='producer',
            name='lead_time_hours',
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AddField(
            model_name='producer',
            name='producer_postcode',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
