# Generated by Django 5.2.11 on 2026-02-20 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_options_rename_user_address_account_and_more'),
        ('producers', '0002_producer_business_address_producer_lead_time_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='user',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='producer_postcode',
        ),
        migrations.AlterField(
            model_name='producer',
            name='business_address',
            field=models.OneToOneField(blank=True, limit_choices_to={'address_type': 'BUSINESS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer_business', to='addresses.address'),
        ),
    ]
