# Generated by Django 5.2.11 on 2026-02-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_rename_user_producer_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='company_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
