# Generated by Django 5.2.11 on 2026-02-26 13:27

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_alter_address_options_and_more'),
        ('producers', '0004_producer_company_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='business_description',
        ),
        migrations.AddField(
            model_name='producer',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='company_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producer',
            name='company_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producer',
            name='lead_time_hours',
            field=models.PositiveIntegerField(default=48, validators=[django.core.validators.MinValueValidator(48)]),
        ),
        migrations.AddIndex(
            model_name='producer',
            index=models.Index(fields=['company_name'], name='producers_p_company_d351bb_idx'),
        ),
    ]
