# Generated by Django 5.2.12 on 2026-03-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0005_remove_producer_business_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='company_email',
        ),
    ]
